name: Convert PNG to WebP

on:
  push:
    branches:
      - main # Jab bhi tum "main" branch pe push karoge, PNG auto WebP banega

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert PNG to WebP
        run: |
          sudo apt update
          sudo apt install webp -y
          find ./ -name '*.png' -exec sh -c 'cwebp -q 80 "$1" -o "${1%.png}.webp"' _ {} \;
          find ./ -name '*.jpg' -exec sh -c 'cwebp -q 80 "$1" -o "${1%.jpg}.webp"' _ {} \;

      - name: Commit converted images
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Converted PNG/JPG to WebP" || echo "No changes to commit"
          git push
